AWSTemplateFormatVersion: 2010-09-09
Description: Create SSM Parameter Store Parameters of the test.yml.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: System Configuration
        Parameters:
          - Stack
          - Env
      -
        Label:
          default: ParamTest Configuration
        Parameters:
          - ParamTest

Parameters: 
  Stack:
    Description: Type the Name for Stack Tag.
    Type: String
    Default: test
    AllowedPattern: ^[a-z][a-z0-9\-]{1,}[a-z0-9]$

  Env:
    Description: Type the Name for Env Tag. 
    Type: String
    Default: dev
    AllowedValues:
      - prod
      - stage
      - test
      - dev
      - common

  CidrBlock:
    Description: Specify the VPC CidrBlock.
    Type: String
    Default: 172.16.0.0

  PersonalIp1:
    Description: Specify the PersonalIp1.
    Type: String
    Default: 113.37.201.11

  PersonalDescription1:
    Description: Specify the PersonalDescription1.
    Type: String
    Default: access from masaki-ishimoto

  PersonalIp2:
    Description: (Optional) Specify the PersonalIp2.
    Type: String

  PersonalDescription2:
    Description: (Optional) Specify the PersonalDescription2.
    Type: String

Conditions:
  CreateParamCidrBlock:
    !Not [!Equals ['', !Ref CidrBlock]]
  CreateParamPersonalIp1:
    !Not [!Equals ['', !Ref PersonalIp1]]
  CreateParamPersonalDescription1:
    !Not [!Equals ['', !Ref PersonalDescription1]]
  CreateParamPersonalIp2:
    !Not [!Equals ['', !Ref PersonalIp2]]
  CreateParamPersonalDescription2:
    !Not [!Equals ['', !Ref PersonalDescription2]]
  
Resources: 
#------------------------------------#
# SSM Parameter
#------------------------------------#
  SsmParamCidrBlock:
    Condition: CreateParamCidrBlock
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /network/cidrblock
      Type: String
      Value: !Ref CidrBlock
      Tags:
        Stack: !Ref Stack
        Env: !Ref Env
        Name: !Sub ${Stack}-${Env}

  SsmParamPersonalIp1:
    Condition: CreateParamPersonalIp1
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /person1/ip
      Type: String
      Value: !Ref PersonalIp1
      Tags:
        Stack: !Ref Stack
        Env: !Ref Env
        Name: !Sub ${Stack}-${Env}
    
  SsmParamPersonalDescription1:
    Condition: CreateParamPersonalDescription1
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /person1/description
      Type: String
      Value: !Ref PersonalDescription1
      Tags:
        Stack: !Ref Stack
        Env: !Ref Env
        Name: !Sub ${Stack}-${Env}
    
  SsmParamPersonalIp2:
    Condition: CreateParamPersonalIp2
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /person2/ip
      Type: String
      Value: !Ref PersonalIp2
      Tags:
        Stack: !Ref Stack
        Env: !Ref Env
        Name: !Sub ${Stack}-${Env}
    
  SsmParamPersonalDescription2:
    Condition: CreateParamPersonalDescription2
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /person2/description
      Type: String
      Value: !Ref PersonalDescription2
      Tags:
        Stack: !Ref Stack
        Env: !Ref Env
        Name: !Sub ${Stack}-${Env}
